# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b5c19522d366276952b45326ee442904724c01fb9924fdc0894643686669ff2056ee23aa54ea5eafa3fbad541544174a5d83ac40c0e34f42bc8fcc6fc81b7f

test:
  secret_key_base: 231abc9d459950e65c7c080b523ca33171c25c6e2ff585ca4d08cc9fc6b56b20f793668d766a8c02c684458cc69a9ed350a4ff9525e358d9ea7e26562ad80728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
